export const servicesMock = [
  {
    id: "srv-001",
    name: "Home Cleaning",
    category: "Cleaning",
    price: 45,
    durationMins: 90,
    rating: 4.7,
    reviews: 128,
    location: "On-site",
    status: "Available",
    description:
      "Deep cleaning for rooms, kitchen, and bathrooms with eco-friendly products.",
  },
  {
    id: "srv-002",
    name: "Barber Appointment",
    category: "Grooming",
    price: 20,
    durationMins: 30,
    rating: 4.5,
    reviews: 86,
    location: "In-store",
    status: "Available",
    description: "Haircut and beard trim with styling guidance.",
  },
  {
    id: "srv-003",
    name: "Laptop Repair",
    category: "Repairs",
    price: 60,
    durationMins: 120,
    rating: 4.6,
    reviews: 54,
    location: "In-store",
    status: "Limited",
    description:
      "Diagnostics, part replacement recommendations, and performance tuning.",
  },
  {
    id: "srv-004",
    name: "Fitness Coaching",
    category: "Health",
    price: 35,
    durationMins: 60,
    rating: 4.8,
    reviews: 210,
    location: "Online",
    status: "Available",
    description: "Personalized workout plan and weekly check-ins.",
  },
  {
    id: "srv-005",
    name: "Plumbing Visit",
    category: "Home Services",
    price: 70,
    durationMins: 60,
    rating: 4.4,
    reviews: 41,
    location: "On-site",
    status: "Available",
    description: "Fix leaks, clogged drains, and basic pipe maintenance.",
  },
  {
    id: "srv-006",
    name: "Car Wash",
    category: "Auto",
    price: 15,
    durationMins: 25,
    rating: 4.3,
    reviews: 77,
    location: "On-site",
    status: "Unavailable",
    description: "Exterior wash and quick interior vacuum.",
  },
];
export const servicesMock = [
  {
    id: "srv-001",
    name: "Home Cleaning",
    category: "Cleaning",
    price: 45,
    durationMins: 90,
    rating: 4.7,
    reviews: 128,
    location: "On-site",
    status: "Available",
    description:
      "Deep cleaning for rooms, kitchen, and bathrooms with eco-friendly products.",
  },
  {
    id: "srv-002",
    name: "Barber Appointment",
    category: "Grooming",
    price: 20,
    durationMins: 30,
    rating: 4.5,
    reviews: 86,
    location: "In-store",
    status: "Available",
    description: "Haircut and beard trim with styling guidance.",
  },
  {
    id: "srv-003",
    name: "Laptop Repair",
    category: "Repairs",
    price: 60,
    durationMins: 120,
    rating: 4.6,
    reviews: 54,
    location: "In-store",
    status: "Limited",
    description:
      "Diagnostics, part replacement recommendations, and performance tuning.",
  },
  {
    id: "srv-004",
    name: "Fitness Coaching",
    category: "Health",
    price: 35,
    durationMins: 60,
    rating: 4.8,
    reviews: 210,
    location: "Online",
    status: "Available",
    description: "Personalized workout plan and weekly check-ins.",
  },
  {
    id: "srv-005",
    name: "Plumbing Visit",
    category: "Home Services",
    price: 70,
    durationMins: 60,
    rating: 4.4,
    reviews: 41,
    location: "On-site",
    status: "Available",
    description: "Fix leaks, clogged drains, and basic pipe maintenance.",
  },
  {
    id: "srv-006",
    name: "Car Wash",
    category: "Auto",
    price: 15,
    durationMins: 25,
    rating: 4.3,
    reviews: 77,
    location: "On-site",
    status: "Unavailable",
    description: "Exterior wash and quick interior vacuum.",
  },
];
